version: 2
jobs:
  build:
    environment:
      PLAYWRIGHT_HTML_REPORT: /tmp/playwright-report
      IMAGE_NAME: playwright-gui-api-example
    docker:
      - image: circleci/openjdk:8-jdk
#      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build&Run Docker image
          command: docker build -t mduuude/$IMAGE_NAME:latest . && docker run -d mduuude/$IMAGE_NAME:latest
      - run:
          name: TEST STAGE
          command: docker ps -a
      - run:
          name: TEST STAGE
          command: docker ps -a
      - store_artifacts:
          path: /tmp/playwright-report
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master