version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout
      - run:
          name: Set up project
          command: |
            npm i -D @playwright/test && 
            npx playwright install && 
            npx playwright install-deps
      - run:
          name: Run API tests
          command: npx playwright test tests/api.spec.ts --project=chromium
      - store_artifacts:
          path: ./playwright-report
          destination: api-report
      - run:
          name: Run GUI tests
          command: npx playwright test tests/gui.spec.ts
      - store_artifacts:
          path: ./playwright-report
          destination: gui-report
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: main